config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: :create
  get "signup" => "users#new"
  
  resource :user_session, only: :create
  get "login" => "user_sessions#new"
  delete "logout" => "user_sessions#destroy"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    # for authlogic
    acts_as_authentic do |c|
    c.login_field = :email
    end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  before_filter :require_login
  
  private
  def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
  end
  
  def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
  end
  
  def require_login
      unless current_user
          redirect_to login_url
          return false
      end
  end
  
  def logged_in?
      current_user_session != nil
  end
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

    skip_before_filter :require_login, only: [:new, :create]

    # GET /login
    def new
        @user_session = UserSession.new
    end

    # POST /user_session
    def create
        @user_session = UserSession.new(params[:user_session])
        
        if @user_session.save
            redirect_to root_url
            else
            render action: :new
        end
    end

    # DELETE /logout
    def destroy
        current_user_session.destroy
        redirect_to login_url
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_filter :require_login, only: [:new, :create]
    
    # GET /signup
    def new
        @user = User.new
    end
    
    # POST /users
    def create
        @user = User.new(user_params)
        
        if @user.save
            redirect_to root_url
            else
            render action: :new
        end
    end
    
    private
    
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>


<% if logged_in? %>
<%= link_to "ログアウト", logout_path, method: :delete %>
<% else %>
<%= link_to "ログイン", login_path %>
<%= link_to "新規登録", signup_path %>
<% end %>

  </body>
</html>

app/views/user_sessions/new.html.erb
<%= form_for @user, url: users_path do |f| %>
<fieldset>
<legend>Sign up</legend>
<p>
<%= f.label :name %>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :empno %>
<%= f.text_field :empno %>
</p>
<p>
<%= f.label :password %>
<%= f.password_field :password %>
</p>
<p>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</p>

<%= f.submit "sign up", class: "btn btn-primary" %>
</fieldset>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, url: users_path do |f| %>
<fieldset>
<legend>Sign up</legend>
<p>
<%= f.label :name %>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :empno %>
<%= f.text_field :empno %>
</p>
<p>
<%= f.label :password %>
<%= f.password_field :password %>
</p>
<p>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</p>

<%= f.submit "sign up", class: "btn btn-primary" %>
</fieldset>
<% end %>